source 'https://rubygems.org'

gem 'cucumber'
gem 'selenium-webdriver'
gem 'rspec'
gem 'rake'
gem 'site_prism'
gem 'pry'
gem 'capybara'
#gem 'site_prism'
#gem 'capybara-screenshot'
#gem 'install snapurl'
